### ISSUE TITLE
opencv parallel_for_ not work in mobile device(IOS & Android)

### ISSUE THREAD

**Issue by Shengnan-Zhu** [iago-suarez/efficient-descriptors#2]
Thanks for your excellent work, I've tried your BAD and HashSIFT descriptors and it works very well! And with opencv greater than 4.0, we can use the parallel_for_ module to speed up the computation of descriptors, it works in my project when in PC. But when I transfer it to my project in mobile device(both ios and android, opencv version > 4.0, by built static lib,), I found the parallel module cannot make any improvement.
I would be thankful for any help!

**Comment by iago-suarez** [comment]
Hi,

Thanks for letting us know! In the experiments that we did, it improved the execution time. Thus, it could be an issue with OpenCV compilation. Could you paste the CMake configuration that is printed when you compile OpenCV?

Another option for you could be to use a different parallel for implementation. For example>
- **OpenMP**: https://stackoverflow.com/questions/1448318/omp-parallel-vs-omp-parallel-for
- **C++17**:  https://stackoverflow.com/questions/63340193/c-how-to-elegantly-use-c17-parallel-execution-with-for-loop-that-counts-an-i

**Comment by Shengnan-Zhu** [comment]
> Hi,
> 
> Thanks for letting us know! In the experiments that we did, it improved the execution time. Thus, it could be an issue with OpenCV compilation. Could you paste the CMake configuration that is printed when you compile OpenCV?
> 
> Another option for you could be to use a different parallel for implementation. For example>
> 
> * **OpenMP**: https://stackoverflow.com/questions/1448318/omp-parallel-vs-omp-parallel-for
> * **C++17**:  https://stackoverflow.com/questions/63340193/c-how-to-elegantly-use-c17-parallel-execution-with-for-loop-that-counts-an-i

Thanks for your reply, the opencv lib I used was not compiled by myself, and I will try another parallel implementation.
