### ISSUE TITLE
time cost in computing decsriptors when use HashSIFT

### ISSUE THREAD

**Issue by Shengnan-Zhu** [iago-suarez/efficient-descriptors#3]
Hi, I've tried your HashSIFT descriptor and it works very well! But we found that the time cost in computing hashsift descriptors（with no parallel_for_） is much slower than opencv SIFT(1000 SIFT keypoints, 261ms vs 80ms in my PC). Is this normal?
Here is part of my sample code:

`

    auto sift = cv::SIFT::create(1000);
    std::vector<cv::KeyPoint> kpts1, kpts2;
    cv::Mat sift_descs1, sift_descs2, hs_descs1, hs_descs2;

    sift->detect(img1, kpts1);
    sift->detect(img2, kpts2);

    auto start = system_clock::now();
    sift->compute(img1, kpts1, sift_descs1);
    sift->compute(img2, kpts2, sift_descs2);
    auto end = system_clock::now();
    std::cout << "SIFT compute descs time: " << duration_cast<milliseconds>(end - start).count() << " ms." << std::endl;

    auto hashsift = upm::HashSIFT::create(6.75, upm::HashSIFT::SIZE_256_BITS);

    start = system_clock::now();
    hashsift->compute(img1, kpts1, hs_descs1);
    hashsift->compute(img2, kpts2, hs_descs2);
    end = system_clock::now();
    std::cout << "HashSIFT compute descs time: " << duration_cast<milliseconds>(end - start).count() << " ms." << std::endl;`

Any help will be grateful!

**Comment by jmbuena** [comment]
Hi @Shengnan-Zhu,

Iago did a very good job taking only the SIFT descriptor computation part from the OpenCV SIFT implementation for HashSIFT. If I remember well, this means that HashSIFT is more efficient than OpenCV's SIFT descriptor implementation when used with keypoint detectors other than SIFT. However, when SIFT descriptor and detector are used together, the OpenCV implementation is faster as the descriptor is reusing results already computed by the detector. The other way around is also true, when using HashSIFT with OpenCV SIFT detector should be slower than OpenCV SIFT detector used with SIFT detector.

So, I think in this case SIFT descriptor is faster because it is reusing part of the job done by the SIFT detector. HashSIFT implentation, on the contrary, has to compute this part every time (it can be used with other detectors other than SIFT). 

Thus, if we want to accelerate HashSIFT when used with SIFT detector, we should check if detector is SIFT and then just call OpenCV's SIFT compute and binarize the descriptor with [this line of code](https://github.com/iago-suarez/efficient-descriptors/blob/dfef2a6bdaee879d2ebcdcac7e020ed321dbe8d5/HashSIFT.cpp#L74).

**Comment by jmbuena** [comment]
How to "fix" for speed HashSIFT used with SIFT detector? I think we should provide a different constructor in this case, where the SIFT detector object is provided and then call the compute method on this object followed by the binarization method in HashSIFT.

**Comment by Shengnan-Zhu** [comment]
> 

Thanks for your reply! As your suggestion, I tried AKAZE and ORB detector to extract keypoints, and compute the descriptors with both opencv SIFT and this HashSIFT(AKAZE: scale_factor 5.0, ORB: scale_factor 1.0) method. The results show that computing descriptors with HashSIFT  is still slower than SIFT.

**Comment by Shengnan-Zhu** [comment]
> How to "fix" for speed HashSIFT used with SIFT detector? I think we should provide a different constructor in this case, where the SIFT detector object is provided and then call the compute method on this object followed by the binarization method in HashSIFT.

So you mean that we can use the detectAndCompute result of opencv SIFT and just add a binarization part to get a binarized descriptor?

**Comment by jmbuena** [comment]
> > How to "fix" for speed HashSIFT used with SIFT detector? I think we should provide a different constructor in this case, where the SIFT detector object is provided and then call the compute method on this object followed by the binarization method in HashSIFT.
> 
> @jmbuena So you mean that we can use the detectAndCompute result of opencv SIFT and just add a binarization part to get a binarized descriptor?

Yep. This is what I mean.

If you look at the paper: 

![imagen](https://user-images.githubusercontent.com/3239151/205023100-5977848e-9a5d-4cbc-89e8-f4c3dd5f0814.png)

We do just that, we depart from the SIFT descriptor and we binarize it multiplying by the learnt matrix B and taking the sign of every resulting number. This is the code that it is at method [HashSIFT::matmulAndSign](https://github.com/iago-suarez/efficient-descriptors/blob/dfef2a6bdaee879d2ebcdcac7e020ed321dbe8d5/HashSIFT.cpp#L81). 

JM.

**Comment by jmbuena** [comment]
> @jmbuena Hi, Thanks for your reply! As your suggestion, I tried AKAZE and ORB detector to extract keypoints, and compute the descriptors with both opencv SIFT and this HashSIFT(AKAZE: scale_factor 5.0, ORB: scale_factor 1.0) method. The results show that computing descriptors with HashSIFT is still slower than SIFT.

@Shengnan-Zhu , this is strange to me. This should not be happening. Maybe OpenCV SIFT has a faster implementation now and HashSIFT is using and older and solower OpenCV SIFT descriptor implementation. What version of OpenCV are you using?

**Comment by Shengnan-Zhu** [comment]
> > @jmbuena Hi, Thanks for your reply! As your suggestion, I tried AKAZE and ORB detector to extract keypoints, and compute the descriptors with both opencv SIFT and this HashSIFT(AKAZE: scale_factor 5.0, ORB: scale_factor 1.0) method. The results show that computing descriptors with HashSIFT is still slower than SIFT.
> 
> @Shengnan-Zhu , this is strange to me. This should not be happening. Maybe OpenCV SIFT has a faster implementation now and HashSIFT is using and older and solower OpenCV SIFT descriptor implementation. What version of OpenCV are you using?

@jmbuena The opencv version I use is 4.6.0.

**Comment by jmbuena** [comment]
Thinking it twice, it is reasonable HashSIFT being slower than SIFT, we have to compute the binarization of every SIFT descriptor.

JM

**Comment by Shengnan-Zhu** [comment]
> Thinking it twice, it is reasonable HashSIFT being slower than SIFT, we have to compute the binarization of every SIFT descriptor.
> 
> JM

@jmbuena 
Yes, but I found this step [HashSIFT::matmulAndSign](https://github.com/iago-suarez/efficient-descriptors/blob/dfef2a6bdaee879d2ebcdcac7e020ed321dbe8d5/HashSIFT.cpp#L81) only cost a little time(1-2ms) for 1000 keypoints.

**Comment by jmbuena** [comment]
> > Thinking it twice, it is reasonable HashSIFT being slower than SIFT, we have to compute the binarization of every SIFT descriptor.
> > JM
> 
> @jmbuena Yes, but I found this step [HashSIFT::matmulAndSign](https://github.com/iago-suarez/efficient-descriptors/blob/dfef2a6bdaee879d2ebcdcac7e020ed321dbe8d5/HashSIFT.cpp#L81) only cost a little time(1-2ms) for 1000 keypoints.

I should add, this is reasonable only when using the same implementation of SIFT descriptor extraction.

**Comment by iago-suarez** [comment]
Hi guys, 

I did a quick test with OpenCV 4.5.5. I executed the following code:

```C++
#include "HashSIFT.h"
#include "BAD.h"

using namespace upm;
using namespace std::chrono;

int main(int argc, char *argv[]) {
  std::cout << "Evaluating description time..." << std::endl;
  // NOTE: This piece of code is only valid for measuring execution time. For real matching, the scale of ORB
  // keypoints should be adapted before using SIFT descriptor.
  const int N_TRIALS = 100;

  cv::Mat patternImg = cv::imread("imgs/pattern.jpg", cv::IMREAD_GRAYSCALE);
  cv::resize(patternImg, patternImg, cv::Size(450, 580));

  // Detect keypoint with ORB
  auto detector = cv::ORB::create(1000);
  std::vector<cv::KeyPoint> keypoints;
  detector->detect(patternImg, keypoints);

  // Describe with OpenCV SIFT
  auto sift = cv::SIFT::create(1000);
  auto start = system_clock::now();
  cv::Mat descrs;
  for (int i = 0; i < N_TRIALS; i++) {
    sift->compute(patternImg, keypoints, descrs);
  }
  auto end = system_clock::now();
  auto sift_desc_time = duration_cast<milliseconds>(end - start).count();

  // Describe with HashSIFT (SIFT without DoG Pyramid and binarization)
  auto hashsift = HashSIFT::create(1.0f, HashSIFT::SIZE_512_BITS);
  start = system_clock::now();
  for (int i = 0; i < N_TRIALS; i++) {
    hashsift->compute(patternImg, keypoints, descrs);
  }
  end = system_clock::now();
  auto hashsift_desc_time = duration_cast<milliseconds>(end - start).count();

  std::cout << "SIFT compute descs time: " << sift_desc_time << " ms." << std::endl;
  std::cout << "HashSIFT compute descs time: " << hashsift_desc_time << " ms." << std::endl;
  return 0;
}
```

It should be enough to compare the description time of both descriptors. The results that I obtain are the following:
```
Evaluating description time...
SIFT compute descs time: 3735 ms.
HashSIFT compute descs time: 931 ms.
```

@Shengnan-Zhu could you please execute the same experiment and check what the execution time for you is?
